apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: false   # ensures hash is added when config changes

configMapGenerator:
  - name: policy-reporter-config
    files:
      - config.yaml=policy-reporter-config.yaml
  - name: policy-reporter-kyverno-plugin-config
    files:
      - config.yaml=kyverno-plugin-config.yaml

# patches:
#   - path: patch-configmap.yaml
#     target:
#       kind: ConfigMap
#       name: policy-reporter-config